### ISSUE TITLE
Not able to detect news in RSS-Feed

### ISSUE THREAD

**Issue by Elfangor93** [e-dschungel/rssgoemail#1]
I currently testing this script to be able to send news from a specific feed via Mailman to a group of Users. But apparently, the script is not able to detect news on the feed. I run the script by a cron-job on a hourly base. The first run was successful, but since then no news are detected anymore, even the feed gets update nearly every 15 minutes...
If I run the script manually I get the message: "Nothing to send"
I am monitoring this feed: https://api.20min.ch/rss/view/1

Is there a bug in the script or is my configuration wrong?
[config.zip](https://github.com/e-dschungel/rssgoemail/files/2101068/config.zip)

**Comment by e-dschungel** [comment]
The feed works fine in my setup and I can see no error in your config. Make sure to change the mysql password after you disclosed it here. Did you create the mysql database using config/rssgoemail.sql? Does this table gets new entries on every run? Do you get errors or warnings in log/errors.log?

**Comment by Elfangor93** [comment]
Yes, database seems to be configured correctly. It gets new entries every time when I run the script and no message "Nothing to send" appears. There are also no errors in log/errors.log.

On which criteria is your script deciding that there are new posts in the feed?
When I see a new entry in the feed and I immediately start the script, it doesn't recognize new entry. But it seems, as if the script recognize the new entrys 24 h after the last email was sent...

**Comment by nomadicjosh** [comment]
Hope I can tack onto this issue. I've been having the same issues as @19leunam93. I've been having to manually send the emails because for some reason it is not detecting new items after first run.

**Comment by e-dschungel** [comment]
The script recognizes new posts by a new guid which is not yet in the database. If an email was successfully sent the guids are added to the database. But in this case the problem is the large default configuration value of cacheTime. Reduce it to 60 or so and the problem should be gone.

**Comment by nomadicjosh** [comment]
@e-dschungel Ok, will try that out. Thanks.

**Comment by Elfangor93** [comment]
Yes, that was the problem. After reducing cache to 60, everything works fine.
Thanks a lot for that very helpful script!!

Maybe it would be helpful to explain the effect of the cache value in the README-File...
