### ISSUE TITLE
Compatibility with PHP 8

### ISSUE THREAD

**Issue by sseguin613** [e-dschungel/rssgoemail#10]
Hello, is the script compatible with PHP8? I updated my server to PHP 8 and the script no longer seems to run successfully. 

I am running an older version and not the latest, but I'd just like to check before updating since if it isn't compatible with PHP8, I would hold off on updating since I did a lot of customization for our needs.

Please let me know. Thanks

**Comment by e-dschungel** [comment]
Hi, yes the script is compatible with PHP 8. The dependencies Simplepie and PhpMailer are also PHP8 compatible in recent versions. You can check your own customization by running check_code.sh which uses PHPStan. If you still seeing issues I need the PHP error log from `log/error.log` for debugging.
