### ISSUE TITLE
Adding new line separation in Body of email

### ISSUE THREAD

**Issue by sseguin613** [e-dschungel/rssgoemail#11]
Hello, I would like to know if there is a way to add new lines or separate the text in the body of the email.

Currently I am trying to put this to get each on a separate line and with some separation but it just displays the <br>

$rge_config['emailBody'] = "##ITEM_TITLE## <br> ##ITEM_DATE## <br>
##ITEM_LINK## <br><br><br> ##ITEM_CONTENT##
";

Is there some other way to do that or it is all one line no matter what I would do?

Thanks.

**Comment by e-dschungel** [comment]
Hello,

yes separating with newline is the right way. Your example should work. What's the result you are getting?

**Comment by sseguin613** [comment]
I see the text separated by <br> in the email body. It seems to be putting them as regular text rather than formatting.

**Comment by e-dschungel** [comment]
so the placeholders like ##ITEM_TITLE## are not replaced when you are using newlines in $rge_config['emailBody']?

Whats your PHP and your RSSGoEmail version?

**Comment by sseguin613** [comment]
Both are the latest versions.

the placeholders are replaced by the appropriate RSS text. I am just saying if I put <br> it doesn't get replaced by a new line but shows <br> in the email.

Should I just put a blank new line or should I be using <br>

**Comment by e-dschungel** [comment]
Sorry, I still did not get your problem. Placeholders are replaced and newlines are shown as newlines. So what is not working according your expectation?

**Comment by sseguin613** [comment]
If I put < br > (no spaces) it doesn't get replaced as a newline it still shows as < br > (no spaces) in the body of the email.

**Comment by e-dschungel** [comment]
Ah, now it got it. No HTML tags are not supported/replaced at the moment. Just use a newline instead. Or use \n or \r\n if you want it all in one line.
