### ISSUE TITLE
Feed Error - cURL error 28

### ISSUE THREAD

**Issue by xawwnee** [e-dschungel/rssgoemail#14]
I am getting following error.

```
Feed Error
cURL error 28: Operation timed out after 10002 milliseconds with 0 bytes received    
```

Can not find anything work around.

**Comment by e-dschungel** [comment]
Hi,

that's a error from the underlying curl. Either the given feed url is wrong, the server is temporarily unavailable or the connection is forbidden from server side. Can curl alone (installed in Linux or Windows) get the feed content?

**Comment by xawwnee** [comment]
> Hi,
> 
> that's a error from the underlying curl. Either the given feed url is wrong, the server is temporarily unavailable or the connection is forbidden from server side. Can curl alone (installed in Linux or Windows) get the feed content?

Thanks for your reply.

Server and Feed are fine. It's just some functions which takes some time to generate rss, that's causing the issue.
Still finding to get it work.

**Comment by e-dschungel** [comment]
Curl (used by library SimplePie) is timing out after 10s because it does not get a response from the feed server. That's nothing inside RSSGoEmail.

**Comment by xawwnee** [comment]
fixed it by setting timeout time.

**Comment by e-dschungel** [comment]
ok, fine, closing then
