### ISSUE TITLE
Minimum php 8.2.0

### ISSUE THREAD

**Issue by mdlaat** [e-dschungel/rssgoemail#15]
Just an fyi:

Notes from v0.5.0 mention:
> minimal PHP Version increased to 8.1

However, when using php 8.1.29 I get the following error

> Composer detected issues in your platform:
> 
> Your Composer dependencies require a PHP version ">= 8.2.0". You are running 8.1.29.

Using php 8.2.0 the error dissappears.

So it seems the minimum php is not 8.1, but 8.2

**Comment by e-dschungel** [comment]
Hi mdlaat,

thanks for the report, fixed with 0.5.1
