### ISSUE TITLE
Does this work? Possible database table problem

### ISSUE THREAD

**Issue by Legalien** [e-dschungel/rssgoemail#2]
This project seems to be exactly what I need, but I can't seem to get it to work. I'm kind of a noob with all this stuff by the way.

Let me know if this doesn't work for some reason, so that I can stop trying?

**Assuming that it does work...**

So I downloaded the file, uploaded it on my server (Hostgator), and created the database, and uploaded the rssgoemail.sql file, and set up the cron job. I also edited the config file to reflect my setup.

Now, the cron job seems to run correctly, but I don't get an email notification of my feed being updated (even though the feed has new content on it). I suspect it may have something to do with the sql database/table.

The reason I suspect this is because I would imagine the table would get populated after the first time Cron runs, so that it has something to compare to when it runs again to decide whether there are new items on the feed or not.

And here's my feed - https://ninomaluri.com/FreshRSS-master/p/i/?a=rss&hours=168

I hope you can help me. Thank you :)

**Comment by Legalien** [comment]
In error log I get this every time cron runs:

[03-Nov-2018 10:30:02 America/Chicago] PHP Warning:  require_once(/home3/ME/public_html/MYSITE.com/rssgoemail-master/vendor/autoload.php): failed to open stream: No such file or directory in /home3/ME/public_html/MYSITE.com/rssgoemail-master/rssgoemail.php on line 29

[03-Nov-2018 10:30:02 America/Chicago] PHP Fatal error:  require_once(): Failed opening required '/home3/ME/public_html/MYSITE.com/rssgoemail-master/vendor/autoload.php' (include_path='.:/opt/php56/lib/php') in /home3/ME/public_html/MYSITE.com/rssgoemail-master/rssgoemail.php on line 29

Could this be the problem? There's no "**vendor**" folder in Rssgoemail.

How to fix it?

Thanks :)

**Comment by Legalien** [comment]
Oh brother, I think I figured it out. I downloaded the wrong file from Github, and it didn't include the Vendor folder, and so that was the problem. So I downloaded the correct file and uploaded it and everything, and it seems to be working now. I'm just testing it out.

Thanks so much for this script. It's super elegant and does exactly what it needs to do. I love it 😃

**Comment by e-dschungel** [comment]
Thanks for figuring it out yourself. I'm closing this then. I improved README.md  of which file to use for ZIP install.
