### ISSUE TITLE
Script always detects Facebook posts as new

### ISSUE THREAD

**Issue by Legalien** [e-dschungel/rssgoemail#3]
Let me just say that what you created here is beautiful. It's simple and it works! I have encountered 1 problem though and I can't figure it out.

I initially set up Rssgoemail and I added 7 feeds to it. That's 4  for Twitter, 2 for Facebook and 1 for Instagram. I set up my cache at 25 minutes, and my Cron at 30 minutes. I also set the cache and cron for my RSS feeds at 30 minutes (I use FreshRSS for the feeds).

Everything worked perfectly. However, for some reason the script would always recognize the latest posts from my Facebook feeds as new, and send me 1 email per hour that there's updates, even though there weren't any.

See - 
![mmm](https://user-images.githubusercontent.com/44560211/47999155-f10a4880-e101-11e8-919e-5779b69ce24f.PNG)

As soon as I removed the 2 Facebook feeds from Rssgoemail, these routine emails stopped arriving, and I only get emails now when my feeds actually have new updates on them.

All of my feeds are created using self-hosted FreshRSS, so I would imagine they all have the same structure. I tried finding a solution. Reducing/increasing cache and cron times, adding/removing feeds, but I can't figure it out and I don't know what to do. I'm not really super skillful at RSS and coding.

Any ideas why the Facebook posts are always being picked up as new every hour? Thank you 😃

**Comment by e-dschungel** [comment]
Hi,

the detection of new entries is based on the SimplePie get_id() function, which uses the title, the permalink and the content:
`		return call_user_func($fn,
		       $this->get_permalink().$this->get_title().$this->get_content());
`
If anything of that changes, an entry is considered as new. I dont understand how you generate your feed from Facebook, but my guess is that the permalink changes for the facebook generated feed. This can be checked if you open the feed in the browser and look at the source code of the feed. Does that help?

**Comment by Legalien** [comment]
Thank you for the detailed reply.

So I opened the feed and checked, and I don't know if that's it, but it has:

`<guid isPermaLink="false">XXX</guid>`

However, it has the same thing for Facebook and Instagram and Twitter, and all the feeds I create with it. But the problem is only happening for Facebook posts. I create the feeds with self-hosted FreshRSS.

Example Facebook feed - https://ninomaluri.com/FreshRSS/p/i/?a=rss&get=f_14&hours=168
Example Twitter feed - https://ninomaluri.com/FreshRSS/p/i/?a=rss&get=f_15&hours=168

But last night I added a different feed, again with Facebook posts on it, and again Rssgoemail kept sending me emails every hour. But that different feed doesn't have **isPermaling="false"** in it. This new feed was created with self-hosted RSS Bridge.

Example Facebook feed - https://ninomaluri.com/rss-bridge/?action=display&bridge=Facebook&u=https%3A%2F%2Fwww.facebook.com%2Fsocialesale%2F&media_type=all&limit=5&_cache_timeout=1800&format=Atom
Example Twitter feed - https://ninomaluri.com/rss-bridge/?action=display&bridge=Twitter&u=Nino_Maluri&_cache_timeout=1800&format=Atom

So now I'm at a loss. The one thing I Suspect could be the issue is the way Facebook started generating post URLs since a few months ago. See this is what a Facebook post URL used to look like:

https://www.facebook.com/socialesale/posts/998369760311712

And this is how it looks like now:

https://www.facebook.com/socialesale/posts/998369760311712?__xts__%5B0%5D=68.ARCkyeYZNkhXGuIbSNz6fYlEk4cNB8M5lyizddvo-E1ISXrULRzDmehKHUOcR6ixipToyfrSxmC0p3yYgorJWxeZs0UHLardCcUcF-t9Ln6-jIkToFzSNEAr7A_Jt9hdkFe7GndK1OqbtCbVPLBnAMXS4A-0U2fgw2K2zkrSHe7EMvC46q9LoAurK7abkEowrDYk0sVXXDYD0HtAFE1a&__tn__=-R

This is the same link actually, just Facebook appends a bunch of random characters at the end of it by default. Maybe, just maybe, that random string of characters that's appended on every Facebook post isn't static, but changes every hour or something. And so then Rssgoemail picks it up as a unique link and serves it again and again.

I don't know man... I'll try to edit this:

`return call_user_func($fn, $this->get_permalink().$this->get_title().$this->get_content());`

To this:

`return call_user_func($fn, $this->get_title().$this->get_content());`

And then see if Rssgoemail is still sending me Facebook updates every hour. If the hourly emails stop then at least I'll have pinpointed the problem.

If you have any ideas let me know. Thanks again 😃

**Comment by Legalien** [comment]
Okay, I tried what I told you with removing `$this->get_permalink().` but still the old Facebook posts are recognized as new and I get the email every hour.

I also asked about this over at RSS Bridge (since that's what I'm using the create the feeds). They told me:

**In theory, the detection of a new item should only be based on the uri of the element.
In most of the bridges, the content never changes if the uri is similar, but with Facebook Bridge, it changes due to Facebook adding a tracking code to every URL.**

They also told me:

**Both RSS-Bridge and Rssgoemail share the culprit:**

**The get_id function should only base itself on the URI**
**The content should not change if the URI is similar.**
**I have pushed an update that should remove Facebook's tracking codes from their URIs. This should fix your problem.**

So I will add the `$this->get_permalink().` back in the file again. And I will see what happens over at RSS Bridge, maybe I get a solution.

I will report what happens. If you have any thoughts let me know 😃

**Comment by e-dschungel** [comment]
Yeah, if facebook is adding a (changing) tracking code to the URL the change detection wont work. The technical correct solution is to make Facebook stop doing that but that wont happen. You can open an issue over at [SimplePie](https://github.com/simplepie/simplepie)  like to. I don't see it in the scope of rssgoemail to take care of that issue. Anyhow, let me know what happens.

**Comment by Legalien** [comment]
So a person over at RSS Bridge made the update to their Facebook file (it's the file responsible for creating the Facebook feed) and so now what this update does is it removes the Facebook's tracking code. I did the update to the file on my server and tested it out. It worked, but not all the way it seems. I'm still testing it out though.

See what was happening before is I had 2 feeds that contain Facebook posts in Rssgoemail. Each feed contained 5 Facebook posts. And every hour Rssgoemail would send me an email which would include all 5 posts from both feeds, as if each of them was a new post every hour. However what happens now is I still receive the email, but there's only 1 post on it. The latest post from one of the pages.

But an hour just went by and I didn't receive the email! 👍 I'm still testing it out though. I'll report back in a few hours. There's a good chance the problem has been solved. Fingers crossed 🤞 😃

**Comment by Legalien** [comment]
So here's what happened. I implemented the FacebookBridge update the guys on RSS Bridge did and set up my 2 Facebook feeds like before. That's 2 Facebook feeds each containing 5 posts on it. Before the update I would receive an email every hour with all 5+5=10 posts in it. Like so:

![ssasa](https://user-images.githubusercontent.com/44560211/48098563-720a3280-e21d-11e8-9e57-2a8fbd96310f.PNG)

One post is missing from the screenshot... no matter...

After the update I'm still receiving the email every hour, but now it only has 1 post in it. It's the latest post from one of the pages. Like so:

![zzzzzzzzzzz](https://user-images.githubusercontent.com/44560211/48098732-d4633300-e21d-11e8-86aa-eea962c15fb7.PNG)

And that's not a pinned post or anything weird. It's just a normal regular post.

So now I'm thinking the update they did on RSS Bridge worked, but not all the way. But I didn't want to come bother you or them before I tested it some more, so what I did was I created 2 new feeds of different Facebook pages and I added them to Rssgoemail. The first run happened and the new feeds content was loaded and cached. Then on the hour I received the email again, containing only that 1 post from that same 1 Facebook feed as before. Then another hour went by, and again the same thing happened.

By the way, just for testing purposes, the 2 new feeds I added, one of them has a Pinned post and the other doesn't. You know how you can pin a post to always be on top of the Facebook page.  But no, everything works fine on all feeds except that one feed and that one post.

I hate it when it doesn't make sense. I don't have much coding/rss/magic knowledge to fall back on, so when it doesn't make sense then there's nothing I can try. That one Facebook page/post that's being problematic, that page tends to update once per day. So when it updates again today or tomorrow I'll see if it continues sending me that same email/post every hour or not - at this point it wouldn't be the latest post, but the second in line - or if it now starts sending me the latest post every hour, or if it stops doing this.

That's all I've got. I mean, the problem is basically solved, but for that one little annoying page that seems stuck in some weird loop. Any ideas?

**Comment by Legalien** [comment]
I fixed everything man. I got it working perfectly now.

At the end I had to remove `$this->get_content()` to get it working perfectly. Something about the tag in the Instagram links in Facebook posts. Something like that was the last problem, and removing get_content solved it.

Thanks again for this project. It's simple and works perfectly and it's exactly what I was looking for 👍 😃

**Comment by e-dschungel** [comment]
Glad to were able to solve it on your own. I guess Instagram has a changing tracking code inside the url which changes the content of facebook post.
