### ISSUE TITLE
E-Mail format + feed name in subject

### ISSUE THREAD

**Issue by sjeschke** [e-dschungel/rssgoemail#5]
Hi,

i'm not sure if this is the right place for these questions ...

I'm using your program and it works, but now i'd like to do some modifications, but i'm to stupid to change the code myself :)

1. Question is solved in issue 4 👍 
2. Is it possible to change the format of the generated emails? At the moment Outlook displays it with Times New Roman 10.
3. I have multiple feeds, is it possible to include the name of the feed into the subject?

Thanks in advanced and regards from Germany
Steffen

**Comment by e-dschungel** [comment]
Hi Steffen,

yes it is.

1. Fine ;)
2. The mails have no formatting at all. They are plain text. Use your outlook setting to display it the way you like.
3. Sure just modify the mail sending line from #4  to something like `$send = mail_utf8($rge_config['emailTo'], $rge_config['emailFrom'],  $item->get_feed()->get_title(), $accumulatedText);	//use feed name as subject`

Regards
e-dschungel

**Comment by sjeschke** [comment]
Thanks for your reply, but i think i'm to stupid for this stuff :(

I change it like your suggestion and the subject changed to the title of the feed, but the accumulated text is the same for every email and contains the description of all items in one email ...

Finally and in my dreams :) i'd like a subject which looks like this --> [feed_title] - item_title 

PS: Is it possible to have more than one recipient?
PPS: Big thanks for your help!

**Comment by e-dschungel** [comment]
So you want one mail per item? This is accomplished by the code in https://github.com/e-dschungel/rssgoemail/issues/4#issuecomment-436016436 or at least should be ;)

In that code change the sending line to:
`$send = mail_utf8($rge_config['emailTo'], $rge_config['emailFrom'],  "[" . $item->get_feed()->get_title() . "] - " . title, $accumulatedText); //subject [feed_title] - item_title`
and your dream comes true :)

Multiple receipients can be given like ` $rge_config['emailTo']  = "user1@example.com, user2@example.com";`

**Comment by e-dschungel** [comment]
Hi Steffen,

did it work?

**Comment by sjeschke** [comment]
Hi and a big sorry for my very very late reply :(

Everything worked like a charme and made me very happy :)

**Comment by e-dschungel** [comment]
The new version v0.3 allows a mail per item by configuration.
