### ISSUE TITLE
Description, Enclosure and pubDate required

### ISSUE THREAD

**Issue by xawwnee** [e-dschungel/rssgoemail#7]
How to get Description, Enclosure and pubDate required as placeholder

**Comment by e-dschungel** [comment]
Write an isuse like this one ;)

Description: can be added easily for both item and description, will do that after rest is clarified 
enclosure: how do you expected that to be handled? Including a link to the media file in the mail?
pubDate: available for Items as ##ITEM_DATE##, so you like to have the pubDate of the whole feed?

**Comment by xawwnee** [comment]
Placeholders required for each Item nodes e.g Description and Enclosure link.
pubDate: available for Items as ##ITEM_DATE## (Yes, available)
Update: Modified the code as below to fetch Description.

```
		$title = decodeHTMLtoUTF($item->get_title());
		//$desc = htmlspecialchars(trim(preg_replace('/\s\s+/', ' ', $item->get_content())));
		$desc = $item->get_content();
		//$desc = preg_replace("/\"/","'",$desc); // replace double quotes from string to single quotes
		$guid = $item->get_id(true);
		$date = $item->get_date($rge_config['dateFormat']);
		$link = $item->get_link();
        $feed_title = $item->get_feed()->get_title();
        $replacements = array(
            "##ITEM_TITLE##" => $title,
			"##ITEM_DESC##" => $desc,
            "##ITEM_DATE##" => $date,
            "##ITEM_LINK##" => $link,
            "##FEED_TITLE##" => $feed_title,
        );
		//echo $desc; //print for debug
```

**Comment by xawwnee** [comment]
What's storing in GUID?

**Comment by e-dschungel** [comment]
GUID is a unique ID of the item. It is used to determine if this item has been sent before.

**Comment by xawwnee** [comment]
> GUID is a unique ID of the item. It is used to determine if this item has been sent before.

Which information is stored, does it store and match with full feed items eg. title, description, date, link etc?

**Comment by e-dschungel** [comment]
It relies on SimplePie's get_id function with a hashed value. It is a md5-hash over permalink, title and content:
https://github.com/simplepie/simplepie/blob/98ab0fe9f5c04e72c2015eb2ba6a4bedff2dabd1/library/SimplePie/Item.php#L249

**Comment by xawwnee** [comment]
Thanks :)

**Comment by e-dschungel** [comment]
I just pushed a v0.3.1 which adds new placeholders. Unfortunately there seems to be no easy way to get the pubDate of the feed. But I'm happy to receive PRs to add that.

**Comment by xawwnee** [comment]
> I just pushed a v0.3.1 which adds new placeholders. Unfortunately there seems to be no easy way to get the pubDate of the feed. But I'm happy to receive PRs to add that.

Appreciated your work :)

**Comment by xawwnee** [comment]
Well I have customized RSS script as per my requirement.
`'enclosure' => $node->getElementsByTagName('enclosure')->item(0)->attributes['url']->nodeValue`

rssgoemail changes:
`    foreach($items as $item){

		$title = decodeHTMLtoUTF($item->get_title());
		//$desc = htmlspecialchars(trim(preg_replace('/\s\s+/', ' ', $item->get_content())));
		$desc = $item->get_content();
		//$desc = preg_replace("/\"/","'",$desc); // replace double quotes from string to single quotes
		$guid = $item->get_id(true);
		$date = $item->get_date($rge_config['dateFormat']);
		$link = $item->get_link();
        $feed_title = $item->get_feed()->get_title();
        $replacements = array(
            "##ITEM_TITLE##" => $title,
			"##ITEM_DESC##" => $desc,
            "##ITEM_DATE##" => $date,
            "##ITEM_LINK##" => $link,
            "##FEED_TITLE##" => $feed_title,
        );
		//echo $desc; //print for debug
		// if was send before-> skip
		if(wasGUIDSent($rge_config, $pdo, $guid)){
			continue;
		// if not send it
		}else{
			$text = strtr($rge_config['emailBody'], $replacements);
			
			// Test if string contains the word 
			$matchUrl = "growspaceinc.blogspot.com";
			if(strpos($text, $matchUrl) !== false){
				//die("Post containing Internal link skipped for autoposting.\n");
				die;
			}
			
        	if (empty($text)){
		        echo "Nothing to send for item with GUID $guid\n";
            }

            sendMailAndHandleGUID($text, strtr($rge_config['emailSubject'], $replacements), $rge_config, $pdo, $guid);
		}
	}`
